name: 🎨 Format Code

on:
    push:
        branches:
            - main
            - develop
    pull_request:
        branches:
            - main
            - develop

permissions:
    contents: read

jobs:
    format-dotnet:
        name: Format .NET Files
        runs-on: ubuntu-latest

        steps:
            - name: 📂 Checkout Code
              uses: actions/checkout@v6

            - name: 🔧 Setup .NET
              uses: grovegs/actions/.github/actions/setup-dotnet@v1.2.0
              with:
                  global-json-file: sandbox/ConsoleApplication/global.json

            - name: 🎨 Format .NET ConsoleApplication
              uses: grovegs/actions/.github/actions/format-dotnet@v1.2.0
              with:
                  project: sandbox/ConsoleApplication

            - name: 🎨 Format .NET GodotApplication
              uses: grovegs/actions/.github/actions/format-dotnet@v1.2.0
              with:
                  project: sandbox/GodotApplication

    format-files:
        name: Format Files
        runs-on: ubuntu-latest

        steps:
            - name: 📂 Checkout Code
              uses: actions/checkout@v6

            - name: 🎨 Format YAML Files
              uses: grovegs/actions/.github/actions/format-files@v1.2.0
              with:
                  files: "**/*.{yml,yaml}"
                  ignore-path: ".gitignore"

            - name: 🎨 Format JSON Files
              uses: grovegs/actions/.github/actions/format-files@v1.2.0
              with:
                  files: "**/*.json"
                  ignore-path: ".gitignore"

            - name: 🎨 Format Markdown Files
              uses: grovegs/actions/.github/actions/format-files@v1.2.0
              with:
                  files: "**/*.md"
                  ignore-path: ".gitignore"
